@host=http://localhost:7228
@hostId=bcd
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNjFkNThkMi00NjQ3LTQ1MDktYmExYy0wNTYyMWY1ZTBkOGMiLCJnaXZlbl9uYW1lIjoiU2FpZHVsIElzbGFtIiwiZmFtaWx5X25hbWUiOiJSYWppYiIsImp0aSI6IjI5ODVlYTA2LWYxM2QtNDc3Yy1iYzIwLTU2M2M5MzQ0M2Q3ZSIsImV4cCI6MTcxNjEwMjQ0MiwiaXNzIjoiU2FpZHVsIElzbGFtIFJhamliIiwiYXVkIjoiU29iZXIgRGlubmVyIn0.IWv-feJUzNfPL2bgFoKzr2hMsIX6gYdQXUAeyjtsSGg


POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "averageRating": 4.5,
    "sections": [
        {
            "id": { "value": "00000000-0000-0000-0000-000000000000" },
            "name": "Fast food",
            "description": "just to test",
            "items": [
                {
                    "id": { "value": "00000000-0000-0000-0000-000000000000" },
                    "name": "Pizza",
                    "description": "Tasty pizza"
                }
            ]
        }
    ],
    "hostId": { "value": "00000000-0000-0000-0000-000000000000" },
    "dinnerIds": [
        { "value": "00000000-0000-0000-0000-000000000000" }
    ],
    "menuReviewIds": [
        { "value": "00000000-0000-0000-0000-000000000000" }
    ],
    "createdDateTime": "2020-01-01T00:00:00.0000000Z",
    "updatedDateTime": "2020-01-01T00:00:00.0000000Z"
}
