@host=http://localhost:7228
@hostId=bcd
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNGVkZDFhOC0xNWY0LTRkZWQtODVlNS0zMmNmOWJhZGZjMTAiLCJnaXZlbl9uYW1lIjoiU2FpZHVsIElzbGFtIiwiZmFtaWx5X25hbWUiOiJSYWppYiIsImp0aSI6ImMxMGJjNzcyLTk0MzctNGI0NC04Mjg3LWIzMjJmODlhZjE3ZSIsImV4cCI6MTcxNjE5MzMyNCwiaXNzIjoiU2FpZHVsIElzbGFtIFJhamliIiwiYXVkIjoiU29iZXIgRGlubmVyIn0.FeZW5-LmSZJ2jQskjC9YpVGbnH_86v5M8geiQZx89nc

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Menu Name",
  "description": "Menu description will be here",
  "sections": [
    {
      "name": "1st Section Name",
      "description": "1st section description will be here",
      "items": [
        {
          "name": "1st item name",
          "description": "1st item description will be here"
        },
        {
          "name": "2nd item name",
          "description": "2nd item description will be here"
        }
      ]
    },
    {
      "name": "2nd Section Name",
      "description": "2nd section description will be here",
      "items": [
        {
          "name": "3rd item name",
          "description": "3rd item description will be here"
        },
        {
          "name": "4th item name",
          "description": "4th item description will be here"
        }
      ]
    }
  ]
}
