@host=http://localhost:5071


POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName":"Saidul Islam",
    "lastName":"Rajib",
    "email":"saidul1.is.rajib@gmail.com",
    "password":"Test@123"
}
