@host=http://localhost:5071


POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName":"Rajib Ahmed",
    "lastName":"Raju",
    "email":"saidul2.is.rajib@gmail.com",
    "password":"Test@123"
}
